typography_spectrum: 0.5423743261490017
color:
  brandStrength: 0.21264484524726868
  lightness: 0.8902243869379163
  saturation: 0.599106183508411
  rhythmicContrast: 0.12312136008404195
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.783667029812932
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7d2af9fe-907c-42ca-8e2b-eb66f77b6b15.png
name: Dujok
navigation:
  - name: Fasstrack
    url: 'http://www.as.com'
    type: external
  - name: About us
    id: a64b8149-9506-4abf-bbea-b39645d009f9
    type: content
title: DUJOK Payments
description: Boost your businnes
